name: Release
run-name: ${{ github.actor }} is running Release Actions 🚀
on: [workflow_dispatch,push]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 设置 node 环境
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: npm

      - name: 安装依赖 # jq用于在命令行中解析json
        run: |
          sudo apt install jq
          npm install -g yarn
          yarn

      - name: 执行构建
        id: build
        run: node ./scripts/index.js
        continue-on-error: true

      - name: 输出构建结果
        run: |
          echo "result: ${{ toJSON(steps.build) }}"

      - name: 提交代码
        if: ${{ steps.build.outcome == 'success' }}
        run: |
          git config --global user.name Jock
          git config --global user.email findsource@proton.me
          git add .
          echo release v$(jq -r .version latest.json) | git commit --file -
          git pull
          git push origin master
