name: 测试 Actions

on:
  push:
    branches:
      - dev


jobs:
  check-update:
    if: github.repository == 'jooooock/wrx'
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装依赖
        run: yarn

      - name: 检查微信读书是否更新
        run: node ./scripts/weread.js
