name: 测试 Actions

on:
  push:
    branches:
      - master


jobs:
  check-update:
    if: github.repository == 'jooooock/wrx'
    runs-on: ubuntu-latest

    steps:
      - run: node ./scripts/weread.js

  test:
    if: github.repository == 'jooooock/wrx'
    runs-on: ubuntu-latest

    steps:
      - name: 检查环境
        run: |
          node -v
          yarn -v
          jq --version
          echo "github: ${{ toJSON(github) }}"
