name: 测试 Actions

on:
  push:
    branches:
      - dev


jobs:
  check-update:
    name: 检查微信读书核心js是否有更新
    if: github.repository == 'jooooock/wrx'
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装依赖
        run: yarn

      - name: 检查微信读书是否更新
        run: node ./scripts/weread/check-update.js

  patch-js:
    name: 对核心js打补丁并替换插件目录的overrides
    needs: check-update
    runs-on: ubuntu-latest

    steps:
      - run: node ./scripts/weread/patch.js

  build:
    name: 打包发布
    needs: patch-js
    runs-on: ubuntu-latest

    steps:
      - name: 执行构建
        id: build
        run: |
          node ./script/weread/build.js
          echo "version=v$(jq -r .version latest.json)" >> "$GITHUB_OUTPUT"
          echo "version=v$(jq -r .version latest.json)" >> "$GITHUB_ENV"

      - name: 输出构建结果
        run: |
          echo "result: ${{ toJSON(steps.build) }}"
