name: 测试 Actions

on:
  push:
    branches:
      - dev


jobs:
  check-update:
    if: github.repository == 'jooooock/wrx'
    runs-on: ubuntu-latest

    steps:
      - names: 拉取代码
        uses: actions/checkout@v4

      - run: node ./scripts/weread.js
